### ISSUE TITLE
Hide Folders on WATO to monitoring user Role...

### ISSUE THREAD

**Issue by brahama** [opinkerfi/check_mk#1]
Hi guys,

Is it possible to hide folders on Host in WATO so that if a clientx user enters the Hosts Folder he only sees Clientx Folder and subfolders? Now, although he can only access clientx folder as he is contact of that, but he can see all the rest of theh folders in Main.

Thanks!

**Comment by palli** [comment]
Hey Brahama,

We are just a fork of check_mk repository, we are not check_mk team. Try http://mathias-kettner.com/index.html

Good luck!

**Comment by brahama** [comment]
Uhh.. ok.. thanks for the answerr!
